### PR TITLE
Support querying quarry_p database

### PR DESCRIPTION
**Pull request by dhinus**
quarry_p is a new database containing read-only views mirroring 4 tables from Quarry's own database:
- query
- query_revision
- query_run
- star

The use case for this view is described in T367415: doing stats on query execution times, and on which tables are being queried.

These views should not expose any information that is not already visible from the public Quarry web interface. The "user" and "user_group" table do not have corresponding views, to preserve the privacy of users that have logged in to Quarry but did not create any queries.

Bug: [T367415](https://phabricator.wikimedia.org/T367415)

### CODE REVIEW

**Review by siddharthvp — APPROVED** [review]
Looks good to me, though I haven't tested.

**Comment by dhinus** [comment]
I tried deploying this but trying to make a query against the "quarry" database failed with:
```
"'Replica' object has no attribute 'database_name'"
```

I think that's because I missed a required change in the `get_host_name` function.

**Comment by dhinus** [comment]
@vivian-rook @siddharthvp I pushed a few fixes and deployed this PR to https://quarry.wmcloud.org/ -- it seems to be working correctly.

Screenshot 2024-08-20 at 14 20 12

**Review by siddharthvp — APPROVED** [review]

**Comment by dhinus** [comment]
@vivian-rook do you think this can be merged?

**Comment by vivian-rook** [comment]
I would recommend against deploying off of main in this situation. As it is possible that the changes in the merged PRs or the rebuild of the images have changed things that would impact this PR, even though it was working before. I would recommend deploying off the branch, testing, if it looks good merge it, if it does not deploy off of main to revert the change.

**Comment by dhinus** [comment]
I see, thanks. I did double check the other PR #65 and it seemed unlikely to impact this one, but I agree that in general always deploying from the branch is safer (provided that the branch is rebased on top of the current main).

**Pull request merged**
