### PR TITLE
Advertise on replag

### PR DESCRIPTION
**Pull request by framawiki**
Add a warning while there is replication lag on dbs

Bug: T60841

### CODE REVIEW

**Comment by framawiki** [comment]
Can be seen on https://quarry-dev.wmflabs.org/query/18

**Comment by vivian-rook** [comment]
This seems to fail in the dev env, when I run a query I get
```
SELECT command denied to user 'repl'@'172.18.0.5' for table `heartbeat_p`.`heartbeat`
```

**Review by vivian-rook — CHANGES_REQUESTED** [review]
This seems to cause the local dev environment to fail. I get
```
SELECT command denied to user 'repl'@'172.18.0.5' for table `heartbeat_p`.`heartbeat`
```
When I run a query in the docker-compose env.

**Comment by framawiki** [comment]
> This seems to cause the local dev environment to fail.

You are right, corrected.

**Review by vivian-rook — CHANGES_REQUESTED** [review]
I'm still getting the same error
```
SELECT command denied to user 'repl'@'172.18.0.5' for table `heartbeat_p`.`heartbeat`
```

When I run queries in the docker-compose environment on my laptop.

**Comment by framawiki** [comment]
This new db was added in this PR. Be sure to recreate the "db" container and its volume.

**Review by vivian-rook — APPROVED** [review]

**Pull request merged**
